### Riddler Classic

From Angela Zhou comes one riddle to rule them all:

The Riddler Manufacturing Company makes all sorts of mathematical tools: compasses, protractors, slide rules — you name it!
    
    Recently, there was an issue with the production of foot-long rulers. It seems that each ruler was accidentally sliced at three random points along the ruler, resulting in four pieces. Looking on the bright side, that means there are now four times as many rulers — they just happen to have different lengths.

On average, how long are the pieces that contain the 6-inch mark?

#### Ruler class:

Numpy should keep things kind of fast

Generating a simple ruler class that when instantiated will:
- generate 3 random values between 0 - 12

Methods include:
- random_vals(): Generate 3 random floats between 0-12; return order np array"
- find_six_size(): Determine size of 6; return float

Note: Class not really necessary here, might have slowed things down. But trying to live that OOP life. 

In [85]:
import numpy as np
import statistics

In [51]:
# define a ruler class
class ruler():
    def __init__(self, num):
        self.random = self.random_vals(num) # random cuts
        self.num = num # total cuts
        
    def random_vals(self, num_ran):
        """Generate 3 random floats between 0-12; return order np array"""
        
        # generate 3 random floats between 0 - 12 (ignoring )
        # The below is probably unecessary.
        temp_arr = np.random.uniform(low=0.0000001, high=11.999999, size=(3,))
        
        # return sorted array
        return np.sort(temp_arr)
        
    def find_six_size(self):
        """Determine size of 6; return float"""
        
        # there are 4 options; just generating them all & breaking if a 6 exists in range
        for i in range(self.num+1):
            if i == 0:
                if (6 < self.random[i]):
                    size = self.random[i]
                    break
            elif i != num:
                if (6.0 >= self.random[i-1]) and (6.0 < self.random[i]):
                    size = self.random[i] - self.random[i-1]
                    break
            else:
                if 6.0 > self.random[i-1]:
                    size = 12 - self.random[i-1]
                    break
        
        # return size
        return size

In [52]:
test_1 = ruler(3)
test_2 = ruler(3)

In [53]:
print(test_1.random)
print(test_1.find_six_size())

[0.5111764  1.44545229 6.26252274]
4.817070444041198


In [55]:
# confirm:
6.26252274 - 1.44545229 

4.817070449999999

In [54]:
print(test_2.random)
print(test_2.find_six_size())

[ 0.76753223  5.96490843 10.87652789]
4.911619460466888


In [56]:
# confirm:
10.87652789 - 5.96490843 

4.91161946

In [64]:
test_3 = ruler(3)
print(test_3.random)
print(test_3.find_six_size())

[ 8.01376731  8.14577688 10.94878914]
8.013767308153493


### Run lots of iterations of this

store output & calculate mean

In [95]:
import time

# going to generate a dictionary to store mean across various iterations
final_dict = {}

# various iteration lengths
total_its = [10,100,1000,10000,100000,1000000, 2000000, 10000000]

print('***************************************')

# loop through iteration size:
for its in total_its:
    
    # calculate a time 
    start = time.time()
    res_arr = [] # result array must be new

    # instantiate a bunch of rulers w/ 3 random nums
    objs = [ruler(3) for i in range(its)]
    
    # find length of the piece w/ 6
    for obj in objs:
        # find size of 6
        res_arr.append(obj.find_six_size())

    end = time.time()
    
    # find mean & total time - add to dictionary 
    temp_mean = statistics.mean(res_arr)
    temp_time = end - start
    final_dict[its] = {'time': temp_time, 'mean_len': temp_mean}
    
    # print info
    print(f'Ran {its} iterations')
    print(f'Took {temp_time:.5f} seconds to run.')
    print(f'Average length is {temp_mean:.5f} inches.')
    print('***************************************')

***************************************
Ran 10 iterations
Took 0.80732 seconds to run.
Average length is 5.25553 inches.
***************************************
Ran 100 iterations
Took 0.00202 seconds to run.
Average length is 5.84311 inches.
***************************************
Ran 1000 iterations
Took 0.01393 seconds to run.
Average length is 5.51813 inches.
***************************************
Ran 10000 iterations
Took 0.11473 seconds to run.
Average length is 5.63220 inches.
***************************************
Ran 100000 iterations
Took 1.27011 seconds to run.
Average length is 5.62261 inches.
***************************************
Ran 1000000 iterations
Took 13.45143 seconds to run.
Average length is 5.62369 inches.
***************************************
Ran 2000000 iterations
Took 31.60234 seconds to run.
Average length is 5.62479 inches.
***************************************
Ran 10000000 iterations
Took 135.34307 seconds to run.
Average length is 5.62494 inches.
**