### Riddler Classic: 

https://fivethirtyeight.com/features/can-you-hunt-for-the-mysterious-numbers/

This one is basically an extreme sudoku. 

#### Overview of the Problem:

- There are 24 total squares to fill with digits `1-9`. A brute-force solution would be searching through `9^24` possible matrices. 

To solve this I am going to avoid brute-force and break the problem into steps.

#### Step 1: 

Find possible combinations for each row. Each row is `9^3` possibilities (`729` combinations). 

#### Step 2:

I can then take the possibilities for each row and build out every corresponding matrix. This should be much less than `9^24` matrices. 

#### Step 3:

Check that the bottom row products of each column for a matric match.

In [1]:
from collections import defaultdict
import itertools as it
import numpy as np

# input data
right_solutions = [294,216,135,98,112,84,245,40]
bottom_solutions = [8890560,156800,55566]

In [2]:
def columnSolver(solution):
    """Check all 729 combinations of rows against solution"""
    solList = []
    for digits in it.product(range(1,10), range(1,10), range(1,10)):
        if np.prod(digits) == solution:
            solList.append(list(digits))
        
    return solList


def rowSolver(matrix, row_vals):
    """Determine if input matrix matches the row values"""
    for i, sol in enumerate(row_vals):
        if np.prod(matrix[:,i]) == sol:
            continue
        else:
            return False
    return True

#### Testing Functions Above: 

columnSolver:
- 294 only has 3 possibilities

rowSolver:
- test case:
``` 
1  2  3
2  3  5
3  7  6
```
- should return `True` for `[6, 42, 90]`

In [3]:
input_matrix = np.asarray([[1,2,3], [2,3,5], [3,7,6]])
input_row = [6,42,90]
assert(rowSolver(input_matrix, input_row) == True)

### Solve Problem: 

#### Step 1: 

Build out the various matrices. The problem drops from `9^24` combinations to `2,729,376` combinations

In [4]:
# our dict will store list of possible solutions for each row
solutionsRow = defaultdict(list)

for i, solve in enumerate(right_solutions):
    solutionsRow[i+1] = columnSolver(solve)

# output total combinations of matrices we expect
val = 1
for k, v in solutionsRow.items():
    val *= len(v)
print(val) # total matrices to build out.

2729376


#### Step 2 :Build every matrix possibility

Helpful link for this step: https://stackoverflow.com/questions/38721847/how-to-generate-all-combination-from-values-in-dict-of-lists-in-python


In [5]:
# sort the dictionary
rowNames = sorted(solutionsRow)

# build out all combinations of dictionaries using the .product() method
combinations = it.product(*(solutionsRow[Name] for Name in rowNames))

# build a list 
possible_sols = list(combinations)

# assert this matches our calculation above
assert(val == len(possible_sols))

#### Step 3: Check which matrix matches

Check that the product of columns for a matrix match. If they don't then break out of loop and move to the next matrix.

In [6]:
# now jconvert each list of lists into a matrix of size 8 x 3 for each value in the list
array_list = []
for _ in possible_sols:
    array_list.append(np.array(_))

# store solutions
possible_solutions = []

# iterate through each matrix
for i, solutions in enumerate(array_list):
    if i % 500000 == 0:
        print(f'On step {i} with {len(possible_solutions)} possible solutions found')
    if rowSolver(solutions, bottom_solutions):
        possible_solutions.append(solutions)

# Should only be 1 solution
assert(len(possible_solutions) == 1)

print(possible_solutions[0])

On step 0 with 0 possible solutions found
On step 500000 with 0 possible solutions found
On step 1000000 with 0 possible solutions found
On step 1500000 with 0 possible solutions found
On step 2000000 with 0 possible solutions found
On step 2500000 with 0 possible solutions found
[[7 7 6]
 [9 8 3]
 [9 5 3]
 [7 2 7]
 [8 2 7]
 [7 4 3]
 [5 7 7]
 [8 5 1]]


### Solution: 

Solution is below: 

```
7 7 6
9 8 3
9 5 3
7 2 7
8 2 7
7 4 3
5 7 7
8 5 1
```